---
  - name: Assure pip and boto3 is installed
    apt:
      name: python-pip
      state: present
    become: yes
  - name: Install boto
    pip:
      name: boto
      state: present
    become: yes
  - name: Get subnet to attach to
    ec2_vpc_subnet_facts:
      region: "{{ region }}"
      filters:
        "tag:Name": "private"
    register: private_subnet

  - name: subnet collected
    debug:
      msg: "Subnet is {{ private_subnet.subnets[0].id }}"

  - name: Create hosts
    ec2:
      group: "{{ item.value.security_groups }}"
      instance_type: t2.micro
      key_name: "{{ item.value.keypair }}"
      image: "{{ image }}"
      wait: true
      exact_count: 1
      vpc_subnet_id: "{{ private_subnet.subnets[0].id }}"
      region: "{{ region }}"
      count_tag:
        Name: Lab
      instance_tags:
        Name: "Lab-{{ item.key }}"
        Group: "{{ item.value.metadata.group }}"
        deployment_name: "{{ item.value.metadata.deployment_name }}"
    with_dict: "{{ infrastructure }}"